import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { ThemeProvider } from "@/components/theme-provider";
import ConditionalHeaderFooter from "@/components/showHeaderFooter";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";
const ReduxProvider = dynamic(() => import("@/redux/redux-provider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  manifest: "/manifest.json",
  title: "Frames By Engineers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <ReduxProvider>
            <ThemeProvider attribute="class" defaultTheme="system">
              <Toaster />
              <ConditionalHeaderFooter>
                <div className="p-8">{children}</div>
              </ConditionalHeaderFooter>
            </ThemeProvider>
          </ReduxProvider>
        </body>
      </html>

      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </>
  );
}
